# Site
title:              ðŸš€ Sycer Development
bio:                "The leading provider for Discord Bots within the sneaker resale community. ðŸ‘ŸðŸ“ˆ"
description:        "The leading provider for Discord Bots within the sneaker resale community. ðŸ‘ŸðŸ“ˆ"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/wallpaper.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://sycer.dev

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   fyko

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:    UA-143343077-1
  #verify:
  ad-client:   ca-pub-6440602101104197
  #ad-slot:
#bing-verify:
email:              sycerdev@gmail.com
twitter:            sycerdev
#facebook:           username
github-url:         sycer-dev
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:         sycerdev
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
